_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 30
DATASETS:
  TRAIN: ('chuqui_trainval_base',)
  TEST: ('chuqui_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (85000, 100000)
  # COCO does about 8 epochs (110000 iters, 861271 annotations);
  # chuqui has 2200 annotations
  MAX_ITER: 17600
OUTPUT_DIR: "checkpoints/chuqui/faster_rcnn/faster_rcnn_R_101_FPN_base"
