_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_2shot_combine/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 27
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('kalgoorlie_trainval_all_2shot',)
  TEST: ('kalgoorlie_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (9720,)
  # Both COCO and VOC run for 3200 epochs...
  MAX_ITER: 10800
  CHECKPOINT_PERIOD: 1000
  WARMUP_ITERS: 10
# NOTE INPUT.[MIN|MAX]_SIZE_TRAIN/[MIN|MAX]_SIZE_TEST have been disabled in
# fsdet/engine/defaults.py:DefaultTrainer:build_train_loader
OUTPUT_DIR: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN_ft_fc_all_2shot"
