_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN_ft_novel_10shot_combine/model_reset_combine.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 30
    OUTPUT_LAYER: "CosineSimOutputLayers"
    FREEZE_FEAT: True
  BACKBONE:
    FREEZE: True
  PROPOSAL_GENERATOR:
    FREEZE: True
DATASETS:
  TRAIN: ('kalgoorlie_trainval_all_10shot',)
  TEST: ('kalgoorlie_test_all',)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.001
  STEPS: (54000,)
  # Both COCO and VOC run for 3200 epochs...
  MAX_ITER: 60000
  CHECKPOINT_PERIOD: 10000
  WARMUP_ITERS: 10
OUTPUT_DIR: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN_ft_all_10shot"
