_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 57
DATASETS:
  TRAIN: ('kalgoorlie_train',)
  TEST: ('kalgoorlie_test',)
SOLVER:
  IMS_PER_BATCH: 16
  #STEPS: (210000, 250000)
  # this is actually more epochs than octi does as he uses 1 IMS_PER_BATCH
  #MAX_ITER: 270000
  STEPS: (11954, 15525)
  MAX_ITER: 16875
  BASE_LR: 0.00125
OUTPUT_DIR: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN"
