_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 22
DATASETS:
  TRAIN: ('kalgoorlie_trainval_base',)
  TEST: ('kalgoorlie_test_base',)
SOLVER:
  IMS_PER_BATCH: 16
  STEPS: (12994, 15187)
  # COCO does about 15 epochs: (110000 iters * 16 IMS_PER_BATCH ) / 117264 images;
  # VOC does 17.4 epochs
  # kalgoorlie has 402 images (lol); 402 iters would be 16 epochs; however,
  # octi trains for 729 epochs (lol) (270000 iters but 1 IMS_PER_BATCH).
  # this is also 729 epochs, albeit with an IMS_PER_BATCH of 16
  MAX_ITER: 18317
OUTPUT_DIR: "checkpoints/kalgoorlie/faster_rcnn/faster_rcnn_R_101_FPN_base"
