# from https://bitbucket.org/visionsystemsinc/detectron2/src/275aa23d93945efa2e0abfb7621d4ed79f78f05b/configs/COCO-Keypoints/superpit_kalgoorlie_2019_train_keypoint_rcnn_R_101_FPN_3x.yaml with keypoints disabled
_BASE_: "../Base-Keypoint-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  RESNETS:
    DEPTH: 101
  ROI_HEADS:
    NUM_CLASSES: 57
  KEYPOINT_ON: False
  MASK_ON: False
  ROI_KEYPOINT_HEAD:
    NUM_KEYPOINTS: 4
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  IMS_PER_BATCH: 1
  BASE_LR: 0.00125
DATASETS:
 TRAIN: ('kalgoorlie_train',)
 TEST: ('kalgoorlie_test',)
TEST:
 KEYPOINT_OKS_SIGMAS: (0.079, 0.025, 0.079, 0.025)
 AUG:
  FLIP: False

INPUT:
  #RANDOM_FLIP: "none"
  MIN_SIZE_TRAIN: (1024,)
  MIN_SIZE_TEST: 1024
  MAX_SIZE_TRAIN: 1333
OUTPUT_DIR: "checkpoints/kalgoorlie/faster_rcnn/superpit_kalgoorlie_2019_train_keypoint_rcnn_R_101_FPN_3x"
